name: Cross Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Set up libpcap-dev
        env:
          PCAPV: 1.8.1
        run: |
          sudo apt-get install libpcap-dev flex bison byacc gcc-arm-linux-gnueabi -y
          cd /tmp
          wget http://www.tcpdump.org/release/libpcap-$PCAPV.tar.gz
          tar xvf libpcap-$PCAPV.tar.gz
          cd libpcap-$PCAPV
          export CC=arm-linux-gnueabi-gcc
          ./configure --host=arm-linux --with-pcap=linux
          make

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build
        env:
          PCAPV: 1.8.1
          CC: arm-linux-gnueabi-gcc
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: arm
          CGO_LDFLAGS: "-L/tmp/libpcap-1.8.1"
        run: ./build.sh

      - name: Upload a build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ikago_latest_linux_arm
          path: ikago-*
